// Generated by CoffeeScript 1.6.3
(function() {
  window.Library = (function() {
    function Library() {
      var _this = this;
      $.when(this.buildSections()).done(function() {
        return _this.loadHighlight();
      });
      $('.library-navigation .expander').click(function() {
        return $('.library-navigation').toggleClass('expanded');
      });
      $('.library-code-switch').click(function() {
        return $('.library-content').toggleClass('no-code');
      });
    }

    Library.prototype.buildSections = function() {
      var _this = this;
      return $(".library-section").each(function(i, element) {
        var content;
        content = _this.htmlClean($(element).html());
        _this.setupSection(element, content, $(element).data('label'));
        _this.codeSample(element, content);
        return _this.fixHeights(element);
      });
    };

    Library.prototype.setupSection = function(element, content, label) {
      $(element).html("<div class='library-preview'>");
      $(element).find('.library-preview').html(content);
      return $(element).prepend("<span class='library-section-label'>" + label + "</span>");
    };

    Library.prototype.codeSample = function(element, content) {
      $(element).append("</div><div class='library-code'></div>");
      $(element).find('.library-code').html('<pre><code></code></pre>');
      $(element).find('.library-code pre code').text(content);
      if ($(element).data('code') === false) {
        return $(element).find('.library-code pre').css('visibility', 'hidden');
      }
    };

    Library.prototype.loadHighlight = function() {
      return $.getScript("http://yandex.st/highlightjs/7.3/highlight.min.js", function() {
        hljs.tabReplace = '  ';
        return hljs.initHighlightingOnLoad();
      });
    };

    Library.prototype.fixHeights = function(element) {
      var code, preview;
      preview = $(element).find('.library-preview');
      code = $(element).find('.library-code');
      if ($(preview).height() > $(code).height()) {
        return $(code).height($(preview).height());
      }
    };

    Library.prototype.htmlClean = function(html) {
      var dirtyHtmlArray, leadingSpaces, line, linesArray, _i, _len;
      html = html.replace(/(\r\n|\n|\r)/, '');
      leadingSpaces = html.substr(0, html.indexOf("<"));
      dirtyHtmlArray = html.split(/(\r\n|\n|\r)/g);
      linesArray = [];
      for (_i = 0, _len = dirtyHtmlArray.length; _i < _len; _i++) {
        line = dirtyHtmlArray[_i];
        linesArray.push(line.replace(leadingSpaces, ''));
      }
      return linesArray.join('').trim();
    };

    return Library;

  })();

  $(function() {
    var library;
    return library = new Library();
  });

}).call(this);
